language: perl

perl:
  - "5.16"

services:
  - rabbitmq

install:
  - cpanm --quiet --notest Module::Install::AuthorTests
  - cpanm --quiet --notest Test::Spelling
  - cpanm --quiet --notest Test::Perl::Critic
  - cpanm --quiet --notest Readonly
  - cpanm --quiet --notest Net::AMQP
  - cpanm --quiet --notest AnyEvent
  - cpanm --quiet --notest Devel::GlobalDestruction
